version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  # apt_packages:
  # - plantuml # Add apt packages that you need present in the container here, for example plantuml
  jobs:
    # https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry
    post_create_environment:
      # Install poetry
      # https://python-poetry.org/docs/#installing-manually
      - pip install poetry
      # Tell poetry to not use a virtual environment
      - poetry config virtualenvs.create false
    post_install:
      # Install only 'docs' dependency group. If you do not have docs group, please omit it
      # https://python-poetry.org/docs/managing-dependencies/#dependency-groups
      - poetry install --no-root --only docs

sphinx:
  configuration: src/conf.py